server:
  port: 8080

spring:
  datasource:
    # 앱 실행 전, CREATE DATABASE jwt_test_db;
    url: jdbc:mariadb://localhost:3306/jwt_test_db?characterEncoding=UTF-8&serverTimezone=UTC
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: 12345
    # schema.sql or data.sql 자동 실행 모드
    # 최소 1개 이상의 SQL문이 실행되도록 해야 컴파일 에러가 발생하지 않는다.
    # schema.sql(스키마 생성 SQL)
    # data.sql(INSERT 관련 SQL)
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

logging:
  level:
    org.hibernate.type: trace

devsjh:
  app:
    jwtSecret: key
    jwtExpirationMs: 86400000